### ISSUE TITLE
Fixity Checking and Reporting

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#44]
Periodic, I presume. Who who be the report recipients? Web-available?

**Comment by dbrower** [comment]
Yes. We can make this as complicated as we wish. My current thoughts are this:

The unit of a fixity check is an item. When an item is checked, every bag associated with the item is verified and the most current `item_info.json` is also verified. This part is done (via #16 and #14).

Bendo will keep a database table of all past fixity checks (which could be weeded...that is beyond scope). The database table will also keep a record of the next scheduled fixity check for each item.

The fixity checking is throttled to average XXX GB/hour. When the check routine is ready for a new item it asks the database for the next item whose scheduled time is the farthest in the past. It will then checksum that item, annotate the database with a success or failure and then schedule the next fixity check for the item (in YY months. 10? 12? not sure.), and creates a new table row for the next check. (it only schedules a new check on success). We could also leave creating a new check open to some other external device---that would allow for different kinds of items to be checksumed at different intervals.

There is a web inferface which shows all fixity errors sorted from most recent to least recent. The web interface also allows for adding that item to be rechecked.

I would like just enough interface so that we could write a cron job to poll and send emails on error. I don't want bendo senting emails, that would make its configuration too difficult.

I'm open to other ideas. This isn't a firm design.

**Comment by dbrower** [comment]
The backend work is finished. The web pages to see reports on the progress, and to be able to have cron jobs scrape it still needs to be done. But that is all in ticket #64. I'm copying the relevant parts of the above notes into that ticket.

**Comment by dbrower** [comment]
Also, I removed the throttling behavior, and I set the default fixity check interval to 9 months.
