### ISSUE TITLE
add list action to bendo client

### ISSUE THREAD

**Issue by msuhovec** [ndlib/bendo#60]
bclient list <item> will return a list of files associated with that item.

Question- in a json?

**Comment by dbrower** [comment]
thinking of one per line, like `ls`. for example

    $ bclient ls 458g   # 458g is the item id
    458g/a.txt
    458g/b.txt
    458g/fedora/123456789.nt
    458g/fedora/12djgk469.nt

Have the following command line options:

 * `--version=n` list files for version `n` instead of the most current version
 * `--user` the user token to use in communication with bendo
 * `--long` output a long form for each file `<blob number> <size> <username> <date uploaded> <filename>`

**Comment by msuhovec** [comment]
Don- 

I'm a little unclear about the --user. If this is a general token used across all operations for talking to bendo, OK. If it's ls specific, is it just the creator id of the item? It it's the latter, could we just include the id as a column in the long form?

**Comment by dbrower** [comment]
--user is the token to be used for authentication with the bendo server. Authentication is not enabled right now on the test server, but it will be on the production stuff. I can find the header for that in the spec document for you tomorrow.

**Comment by msuhovec** [comment]
Sorry- mixed up issues 60 and 61
